# Generated by Django 5.1.3 on 2024-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.TextField(default='Описание отсутствует'),
        ),
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(default='Описание отсутствует', upload_to='flowers/'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
