# Generated by Django 5.1.3 on 2024-11-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_flower_description_flower_image_alter_flower_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='flower',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
